{{- if not .Values.token.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "argocd-appset-secret-plugin.fullname" . }}-token
  labels:
    app.kubernetes.io/part-of: argocd
    {{- include "argocd-appset-secret-plugin.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ randAlphaNum 32 | b64enc | quote }}

{{- end }}
