apiVersion: v1
kind: Service
metadata:
  name: {{ include "argocd-appset-secret-plugin.fullname" . }}
  labels:
    {{- include "argocd-appset-secret-plugin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "argocd-appset-secret-plugin.selectorLabels" . | nindent 4 }}
