resources:
  - manifests/configmap.yaml
  - manifests/deployment.yaml
  - manifests/namespace.yaml
  - manifests/plugin-secret.yaml
  - manifests/service.yaml

configMapGenerator:
  - name: env-var-plugin-generator-script
    namespace: argocd
    files:
      - main.py=main.py
