---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-env-var-plugin-generator
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-env-var-plugin-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-env-var-plugin-generator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-env-var-plugin-generator
    spec:
      containers:
        - name: argocd-env-var-plugin-generator
          image: python:latest
          command: ["python"]
          args: ["/app/main.py"]
          imagePullPolicy: Always
          ports:
            - containerPort: 4355
              name: http
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: arogocd-generator-plugin-token
                  key: token
          envFrom:
            - secretRef:
                name: argocd-env-vars
          volumeMounts:
            - name: env-var-plugin-generator-script
              mountPath: "/app/main.py"
              subPath: "main.py"
      volumes:
        - name: env-var-plugin-generator-script
          configMap:
            name: env-var-plugin-generator-script
