---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-secret-plugin-generator
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-secret-plugin-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-secret-plugin-generator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-secret-plugin-generator
    spec:
      containers:
        - name: argocd-secret-plugin-generator
          image: jessebot/argocd-appset-secret-plugin:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4355
              name: http
          volumeMounts:
            - name: token
              mountPath: "/var/run/argocd/token"
              subPath: "token"
            - name: argocd-secret-vars
              mountPath: "/var/run/argocd/secret_vars.yaml"
              subPath: "secret_vars.yaml"
      volumes:
        - name: token
          secret:
            secretName: arogocd-generator-plugin-token
        - name: argocd-secret-vars
          secret:
            secretName: argocd-secret-vars
