apiVersion: v1
kind: Service
metadata:
  name: argocd-env-var-plugin-generator
  namespace: argocd
spec:
  selector:
    app.kubernetes.io/name: argocd-env-var-plugin-generator
  ports:
  - name: http
    port: 80
    targetPort: 4355
