apiVersion: v1
kind: Secret
metadata:
  name: {{ include "argocd-appset-secret-plugin.fullname" . }}-token
  labels:
    {{- include "argocd-appset-secret-plugin.labels" . | nindent 4 }}
data:
  token: {{ randAlphaNum 32 }}

