{{- if eq .Values.secretVars.secretName "argocd-secret-vars-ci-test" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret-vars-ci-test
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
type: Opaque
data:
  secret_vars.yaml: |
    app_name: "cool_app"
{{- end }}
